#' Run Multiple Dose-Finding Simulations in Parallel
#'
#' Executes the `run_trial()` function across \code{n_sim} simulations in parallel, returning a list of results from each run.
#'
#' @param n_sim Integer. Number of simulation replicates to run.
#' @param visits A data frame of visit-level data generated by \code{sim_data()}.
#' @param prior_info A list of prior parameters as returned by \code{get_priors()}.
#' @param dlt_model A list containing the true dose-toxicity model, as returned by \code{true_model()}.
#' @param target_type Character. Either \code{"absolute"} or \code{"relative"} — passed directly to \code{run_trial()}.
#' @param target_dlt_rate Numeric. If \code{target_type = "absolute"}, this is the target DLT rate. If \code{"relative"}, it's the increase above the anchor DLT.
#' @param cohort_size Integer. Number of patients in each follow-up cohort (after the first).
#' @param first_cohort_size Integer. Number of patients in the first cohort.
#' @param starting_dose Numeric. The unscaled starting threshold for the first cohort.
#' @param dose_step_size Numeric. The increment between allowable threshold values.
#'
#' @return A list of length \code{n_sim}, where each element is the full result list returned by \code{run_trial()}.
#'
#' @examples
#' \dontrun{
#' prior_info <- get_priors(...)
#' dlt_model <- true_model(...)
#' visits <- sim_data(...)
#' results_list <- run_simulations(
#'   n_sim = 100,
#'   visits = visits,
#'   prior_info = prior_info,
#'   dlt_model = dlt_model,
#'   target_type = "relative",
#'   target_dlt_rate = 0.05,
#'   cohort_size = 10,
#'   first_cohort_size = 10,
#'   starting_dose = 0.10,
#'   dose_step_size = 0.01
#' )
#' }
#'
#' @export
library(future)
library(future.apply)

run_simulations <- function(n_sim, 
                            visits, 
                            prior_info, 
                            dlt_model, 
                            target_type, 
                            target_dlt_rate, 
                            cohort_size = 10, 
                            first_cohort_size = 10, 
                            starting_dose = 0.10, 
                            dose_step_size = 0.01) {
  
  # Set up parallel processing
  plan(multisession, workers = availableCores())
  
  # Run all simulations in parallel and return all results
  results_list <- future_lapply(1:n_sim, function(i) {
    run_trial(
      visits = visits,
      prior_info = prior_info,
      dlt_model = dlt_model,
      target_type = target_type,
      target_dlt_rate = target_dlt_rate,
      cohort_size = cohort_size,
      first_cohort_size = first_cohort_size,
      starting_dose = starting_dose,
      dose_step_size = dose_step_size
    )
  })
  
  return(results_list)
}
